/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as BriefsRouteImport } from './routes/briefs'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefsExternalIdRouteImport } from './routes/briefs.$externalId'
import { Route as ApiBriefsEnrichRouteImport } from './routes/api/briefs/enrich'

const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsRoute = BriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsExternalIdRoute = BriefsExternalIdRouteImport.update({
  id: '/$externalId',
  path: '/$externalId',
  getParentRoute: () => BriefsRoute,
} as any)
const ApiBriefsEnrichRoute = ApiBriefsEnrichRouteImport.update({
  id: '/api/briefs/enrich',
  path: '/api/briefs/enrich',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/briefs': typeof BriefsRouteWithChildren
  '/candidate': typeof CandidateRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/triage': typeof TriageRoute
  '/briefs/$externalId': typeof BriefsExternalIdRoute
  '/api/briefs/enrich': typeof ApiBriefsEnrichRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/briefs': typeof BriefsRouteWithChildren
  '/candidate': typeof CandidateRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/triage': typeof TriageRoute
  '/briefs/$externalId': typeof BriefsExternalIdRoute
  '/api/briefs/enrich': typeof ApiBriefsEnrichRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/briefs': typeof BriefsRouteWithChildren
  '/candidate': typeof CandidateRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/triage': typeof TriageRoute
  '/briefs/$externalId': typeof BriefsExternalIdRoute
  '/api/briefs/enrich': typeof ApiBriefsEnrichRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/briefs'
    | '/candidate'
    | '/dashboard'
    | '/settings'
    | '/triage'
    | '/briefs/$externalId'
    | '/api/briefs/enrich'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/briefs'
    | '/candidate'
    | '/dashboard'
    | '/settings'
    | '/triage'
    | '/briefs/$externalId'
    | '/api/briefs/enrich'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/briefs'
    | '/candidate'
    | '/dashboard'
    | '/settings'
    | '/triage'
    | '/briefs/$externalId'
    | '/api/briefs/enrich'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BriefsRoute: typeof BriefsRouteWithChildren
  CandidateRoute: typeof CandidateRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  TriageRoute: typeof TriageRoute
  ApiBriefsEnrichRoute: typeof ApiBriefsEnrichRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs': {
      id: '/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof BriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs/$externalId': {
      id: '/briefs/$externalId'
      path: '/$externalId'
      fullPath: '/briefs/$externalId'
      preLoaderRoute: typeof BriefsExternalIdRouteImport
      parentRoute: typeof BriefsRoute
    }
    '/api/briefs/enrich': {
      id: '/api/briefs/enrich'
      path: '/api/briefs/enrich'
      fullPath: '/api/briefs/enrich'
      preLoaderRoute: typeof ApiBriefsEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BriefsRouteChildren {
  BriefsExternalIdRoute: typeof BriefsExternalIdRoute
}

const BriefsRouteChildren: BriefsRouteChildren = {
  BriefsExternalIdRoute: BriefsExternalIdRoute,
}

const BriefsRouteWithChildren =
  BriefsRoute._addFileChildren(BriefsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BriefsRoute: BriefsRouteWithChildren,
  CandidateRoute: CandidateRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  TriageRoute: TriageRoute,
  ApiBriefsEnrichRoute: ApiBriefsEnrichRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
